- copy: src={{ ansible_env.PWD }}/roles/ben_mac/files/dotfiles/.{{ item }}
        dest=~/.{{ item }}
  with_items:
    - bashrc
    - bashrc-custom
    - git-completions
    - git-prompt-info
    - tmux.conf
    - vimrc

- file: src="~/.bashrc"
        path="~/.bash_profile"
        state=link

- name: Base16 shell colours
  git: repo=https://github.com/chriskempson/base16-shell.git
       dest=~/.config/base16-shell

# - file: path=~/.{{ item }} state=directory
#   with_items:
#     - innotop
#     - ssh
#     - ipython
#     - ipython/profile_default
#     - ipython/profile_default/startup

# - file: src={{ ansible_env.PWD }}/roles/adam_mac/files/dotfiles/{{ item }}
#         path=~/.{{ item }}
#         state=link
#   with_items:
#     - gitconfig
#     - gitignore_global
#     - python_startup
#     - ssh/config
#     - ansible.cfg
#     - ipython/profile_default/startup/00-imports.py

# - copy: src=dotfiles/innotop/innotop.conf
#         dest=~/.innotop/innotop.conf
#         force=no  # Only if it doesn't exist

# - name: zsh - git repo for prezto fork
#   git: repo=git@github.com:adamchainz/prezto.git
#        dest=~/.zprezto

# - name: zsh - link in prezto files
#   file: state=link src=~/.zprezto/runcoms/{{ item }} path=~/.{{ item }}
#   with_items:
#     - zlogin
#     - zlogout
#     - zprofile
#     - zshenv
#     - zshrc
#     - zpreztorc
